// Generated by CoffeeScript 1.3.3
(function() {
  var Forgery;

  Forgery = Forgery = {};

  Forgery.version = '0.0.1';

  Forgery.Factory = require('./factory');

  module.exports = Forgery;

}).call(this);
